"""Sync Complaint model

Revision ID: 06e4d0f96887
Revises:
Create Date: 2026-09-26 19:00:19.987754

"""

import sqlalchemy as sa
from alembic import op
from alembic.operations.base import BatchOperations

# revision identifiers, used by Alembic.
revision = "06e4d0f96887"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    batch_op: BatchOperations
    with op.batch_alter_table("complaint", schema=None) as batch_op:
        batch_op.add_column(sa.Column("resolved_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    batch_op: BatchOperations
    with op.batch_alter_table("complaint", schema=None) as batch_op:
        batch_op.drop_column("resolved_at")

    # ### end Alembic commands ###
